name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: run protolint
        uses: plexsystems/protolint-action@v0.7.0

  pr-test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: run buf
        uses: bufbuild/buf-action@v1
        with:
          input: proto
          exclude_paths: "proto/google"
          breaking: false
